apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inventory-manager-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: inventorymanagerteam4.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: inventory-manager-service 
            port:
              number: 80

# kubectl port-forward --address 0.0.0.0 svc/inventory-manager-service 8090:80
