apiVersion: v1
kind: Service
metadata:
  name: inventory-manager-service
spec:
  selector:
    app: inventory-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30666
  type: NodePort
