- name: Deploy Inventory Manager to Kubernetes (Remote VM)
  hosts: k8s_master
  become: yes  # Ensure sudo access

  tasks:
    - name: Copy Kubernetes Deployment YAMLs to VM
      copy:
        src: "./Team4_k8s_App/{{ item }}"  # Ensure this is the correct relative path
        dest: "/home/cedrick/C270Project_Team4/Team4_k8s_App/"
      loop:
        - deployment.yaml
        - service.yaml
        - ingress.yaml

    - name: Apply Kubernetes Manifests
      become: yes
      become_user: cedrick
      shell: |
        if [ ! -f "/etc/kubernetes/admin.conf" ]; then
          echo "Kubeconfig not found!"
          exit 1
        fi
        export KUBECONFIG=/etc/kubernetes/admin.conf
        kubectl apply -f /home/cedrick/C270Project_Team4/Team4_k8s_App/

    - name: Restart Deployment to Pull Latest Image
      become: yes
      become_user: cedrick
      shell: |
        export KUBECONFIG=/etc/kubernetes/admin.conf
        kubectl get deployment inventory-manager-deployment && kubectl rollout restart deployment inventory-manager-deployment || echo "Deployment not found, skipping restart."
