- name: Deploy Inventory Manager to Kubernetes (Remote VM)
  hosts: localhost
  become: yes  # Ensure sudo access

  tasks:
    - name: Copy Kubernetes Deployment YAMLs to VM (local machine in this case)
      copy:
        src: "./Team4_k8s_App/{{ item }}"
        dest: "/home/cedrick/C270Project_Team4/Team4_k8s_App/"
      loop:
        - deployment.yaml
        - service.yaml
        - ingress.yaml

    - name: Apply Kubernetes Manifests
      shell: |
        export KUBECONFIG=$HOME/.kube/config
        kubectl apply -f /home/cedrick/C270Project_Team4/Team4_k8s_App/

    - name: Restart Deployment to Pull Latest Image
      shell: |
        export KUBECONFIG=$HOME/.kube/config
        kubectl rollout restart deployment inventory-manager-deployment
