- name: Deploy Inventory Manager to Kubernetes (Remote VM)
  hosts: k8s_master
  become: yes
  tasks:
    - name: Copy Kubernetes Deployment YAMLs to VM
      copy:
        src: "{{ item }}"
        dest: "/home/{{ ansible_user }}/k8s/"
      loop:
        - deployment.yaml
        - service.yaml
        - ingress.yaml

    - name: Apply Kubernetes Manifests
      shell: kubectl apply -f /home/{{ ansible_user }}/k8s/
      become_user: "{{ ansible_user }}"

    - name: Restart Deployment to Pull Latest Image
      shell: kubectl rollout restart deployment inventory-manager-deployment
      become_user: "{{ ansible_user }}"
