- name: Deploy Inventory Manager to Kubernetes (Remote VM)
  hosts: k8s_master
  become: yes  
  
  tasks:
    - name: Copy Kubernetes Deployment YAMLs to VM
      copy:
        src: "{{ item }}"
        dest: "/home/cedrick/C270Project_Team4/Team4_k8s_App/"
      loop:
        - deployment.yaml
        - service.yaml
        - ingress.yaml

    - name: Apply Kubernetes Manifests
      become_user: cedrick
      shell: /usr/bin/kubectl apply -f /home/cedrick/C270Project_Team4/Team4_k8s_App/

    - name: Restart Deployment to Pull Latest Image
      become_user: cedrick
      shell: /usr/bin/kubectl rollout restart deployment inventory-manager-deployment
