name: Build, Test, and Deploy Inventory App

on:
  push:
    branches:
      - branch11
  pull_request:
    branches:
      - branch11
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t inventory-manager .

      - name: Run Tests - Integration Test
        run: docker run --rm inventory-manager python3 -m pytest tests/test_intergration_inventory_manager_base.py

      - name: Run Tests - Inventory Manager Test
        run: docker run --rm inventory-manager python3 -m pytest tests/test_inventory_manager.py

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image to Docker Hub
        run: |
          docker tag inventory-manager lfrown/inventory-manager:latest
          docker push lfrown/inventory-manager:latest

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/v1.21.0/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Set up Kubernetes Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          kubectl config view --raw

      - name: Apply Kubernetes Manifests Using Ansible (via kubectl)
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/deploy.yml
          inventory: ansible/inventory.ini
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # you might not need SSH if kubectl is set up directly

      - name: Restart Deployment to Pull Latest Image
        run: |
          kubectl rollout restart deployment inventory-manager-deployment
