name: Build, Test, Dockerize, and Deploy to GitHub Pages

on:
  push:
    branches:
      - branch12  # The branch to trigger on
  pull_request:
    branches:
      - branch12  # The branch to trigger on
  workflow_dispatch:  # Allow manual trigger if needed

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code from the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Set up Docker Buildx (necessary for building Docker images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Build the Docker image using the Dockerfile in the repository
      - name: Build Docker Image
        run: docker build -t inventory-manager .

      # 4. Run tests using pytest inside the Docker container
      - name: Run Tests - Integration Test
        run: docker run --rm inventory-manager python3 -m pytest tests/test_intergration_inventory_manager_base.py

      # 5. Run tests for the main inventory manager code
      - name: Run Tests - Inventory Manager Test
        run: docker run --rm inventory-manager python3 -m pytest tests/test_inventory_manager.py

      # 6. Login to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 7. Tag and Push Image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          docker tag inventory-manager lfrown/inventory-manager:latest
          docker push lfrown/inventory-manager:latest

      # 8. Run the application inside the custom Docker network
      - name: Run Application in Background
        run: docker run -d --name inventory-manager-app -p 5000:5000 inventory-manager
        
      # 9. Wait for the application to start (allow enough time for Flask to bind to port 5000)
      - name: Wait for Application to Start
        run: |
          echo "Waiting for Flask to start..."
          timeout=0
          until curl -s http://localhost:5000 > /dev/null || [ $timeout -eq 120 ]; do
            echo "Waiting for Flask..."
            sleep 1
            timeout=$((timeout + 1))
          done
          if [ $timeout -eq 120 ]; then
            echo "Flask app failed to start after 120 seconds!"
            exit 1
          fi
          echo "Flask app is up!"

      # 10. Test if the website is up and running (status code 200)
      - name: Test Website Availability
        run: |
          if curl -s -o /dev/null -w "%{http_code}" http://localhost:5000 | grep -q "200"; then
            echo "The website is running."
          else
            echo "The website is not running."
            exit 1
          fi

  deploy-to-gh-pages:
    runs-on: ubuntu-latest
    needs: build-and-test  # Make sure the build and test job runs first

    steps:
      # 1. Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # 2. Build your static files (optional if you're using a static site generator like Jekyll, Hugo, etc.)
      - name: Build Static Files
        run: |
          # If you need to build the frontend first (e.g., with npm or a static site generator)
          npm install
          npm run build  # Adjust according to your build steps

      # 3. Deploy to GitHub Pages using a GitHub Action for deployment
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./path/to/your/static/files  # Adjust based on where your HTML files are
