name: Build, Test, and Deploy Inventory App

on:
  push:
    branches:
      - branch11
  pull_request:
    branches:
      - branch11
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t inventory-manager .

      - name: Run Tests - Integration Test
        run: docker run --rm inventory-manager python3 -m pytest tests/test_intergration_inventory_manager_base.py

      - name: Run Tests - Inventory Manager Test
        run: docker run --rm inventory-manager python3 -m pytest tests/test_inventory_manager.py

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image to Docker Hub
        run: |
          docker tag inventory-manager lfrown/inventory-manager:latest
          docker push lfrown/inventory-manager:latest

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key for Ansible
        run: |
          echo "Creating SSH directory..."
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          echo "Decoding and writing SSH private key..."
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          echo "Adding SSH key to known hosts..."
          ssh-keyscan -H 192.168.87.132 >> ~/.ssh/known_hosts
        shell: bash

      - name: Debug SSH Key Permissions
        run: |
          echo "Checking SSH directory..."
          ls -lah ~/.ssh

          echo "Checking file permissions..."
          stat ~/.ssh/id_rsa

          echo "Displaying first few lines of the SSH private key (masked)..."
          head -n 5 ~/.ssh/id_rsa | sed 's/./*/g/'
        shell: bash

      - name: Test SSH Connection
        run: ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no cedrick@192.168.87.132 "echo SSH connection successful"

      - name: Debug Ansible Inventory
        run: cat ansible/inventory.ini

      - name: Debug Ansible Inventory Parsing
        run: ansible-inventory -i ansible/inventory.ini --list

      - name: Deploy to Kubernetes via Ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/deploy.yml
          inventory: ansible/inventory.ini
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          options: "-vvv"
