name: Deploy k8

on:
  workflow_run:
    workflows: ["build_inventory.yml"]  # Name of the triggering workflow
    types:
      - completed  # Runs only after the workflow completes
jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Kubernetes deployment
        run: |
          kubectl delete -f deployment.yaml
          kubectl delete -f service.yaml
          kubectl delete -f ingress.yaml
          
      - name: Verify deployment
        run: kubectl get pods -n default
