name: Deploy to Minikube (Remote VM)

on:
  workflow_run:
    workflows: ['Build and Test Inventory App']
    types: [completed]
  workflow_dispatch:  # Allows manual trigger if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: install ssh key
        run: |
          install -m 600 -D /dev/null ~/.shh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_HOST }} > ~/.ssh/known_hosts
      - name: connect and run script
        run: ssh ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} && echo "whoami" && ./k8deployscript
        
   
