name: Deploy to Minikube (Remote VM)

on:
  workflow_run:
    workflows: ['Build and Test Inventory App']
    types: [completed]
  workflow_dispatch:  # Allows manual trigger if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug SSH Key Storage
        run: |
          echo "Checking stored SSH keys..."
          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "Error: SSH_PRIVATE_KEY is empty or not set!"
            exit 1
          else
            echo "SSH key detected, storing securely..."
          fi

      - name: Setup SSH Connection
        run: |
          mkdir -p ~/.ssh
          
          # Store SSH private key securely
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Add VM to known hosts (Prevent SSH host verification issues)
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Test SSH Connection to VM
        run: |
          echo "Testing SSH Connection..."
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} "echo 'SSH Connected Successfully!'"

      - name: Deploy to Minikube on Remote VM
        run: |
          echo "Starting deployment..."
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} << 'EOF'
            set -e  # Exit if any command fails

            echo "Switching to Minikube Docker"
            eval $(minikube docker-env)

            echo "Pulling latest Docker image..."
            docker pull lfrown/inventory-manager:latest || { echo "Docker pull failed"; exit 1; }

            echo "Applying Kubernetes configuration..."
            kubectl apply -f /Team4_k8s_App/deployment.yaml || { echo "Failed to apply deployment"; exit 1; }
            kubectl apply -f /Team4_k8s_App/service.yaml || { echo "Failed to apply service"; exit 1; }

            echo "Restarting deployment..."
            kubectl rollout restart deployment inventory-manager-deployment || { echo "Failed to restart deployment"; exit 1; }
          EOF

      - name: Get Minikube Service URL
        run: |
          echo "Fetching Minikube service URL..."
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} "minikube service inventory-manager-service --url"
