name: Deploy k8

on:
  workflow_run:
    workflows: ["Build Inventory"]  # Match the workflow name from build_inventory.yml
    types:
      - completed  # Runs only after the workflow completes

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Kubernetes deployment
        run: |
          kubectl delete -f Team4_k8s_App/deployment.yaml
          kubectl delete -f Team4_k8s_App/service.yaml
          kubectl delete -f Team4_k8s_App/ingress.yaml
          kubectl apply -f Team4_k8s_App/deployment.yaml
          kubectl apply -f Team4_k8s_App/service.yaml
          kubectl apply -f Team4_k8s_App/ingress.yaml

      - name: Verify deployment
        run: kubectl get pods -n default
