name: Deploy to Minikube (Remote VM)

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Minikube on Remote VM
        run: |
          ssh ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} << 'EOF'
            # Switch to Minikube Docker
            eval $(minikube docker-env)
            
            # Pull Latest Image
            docker pull lfrown/inventory-manager:latest

            # Apply Kubernetes Config
            kubectl apply -f /Team4_k8s_App/deployment.yaml
            kubectl apply -f /Team4_k8s_App/service.yaml

            # Restart Deployment
            kubectl rollout restart deployment inventory-manager-deployment
          EOF

      - name: Get Service URL
        run: |
          ssh ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} minikube service inventory-manager-service --url
