name: Deploy to Minikube (Remote VM)

on:
  workflow_run:
    workflows: ['Build and Test Inventory App']
    types: [completed]
  workflow_dispatch:  # Allows manual trigger if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Deployment Script in VM
        run: |
          echo "🚀 Running deploy.sh in VM..."
          sshpass -p "${{ secrets.VM_PASSWORD }}" ssh -o StrictHostKeyChecking=no cedrick@192.168.87.132 "bash /home/cedrick/C270ProjectTeam4/k8deployscript.sh"

      - name: Debug SSH Connection
        run: |
          echo "🔍 Testing SSH Connection..."
          sshpass -p "${{ secrets.VM_PASSWORD }}" ssh -o StrictHostKeyChecking=no cedrick@192.168.87.132 "
            echo '✅ SSH Connected Successfully!';
            hostname;
            whoami;
            ls -lah /home/cedrick/C270ProjectTeam4/;
          "
