name: Deploy k8

on:
  push:
    branches:
      - branch10  # The branch to trigger on
  pull_request:
    branches:
      - branch10  # The branch to trigger on
  workflow_dispatch:  # Allow manual trigger if needed

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Kubernetes deployment
        run: |
          kubectl delete -f deployment.yaml
          kubectl delete -f service.yaml
          kubectl delete -f ingress.yaml
          
      - name: Verify deployment
        run: kubectl get pods -n default
