name: Deploy to Minikube (Remote VM)

on:
  workflow_run:
    workflows: ['Build and Test Inventory App']
    types: [completed]
  workflow_dispatch:  # Allows manual trigger if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Expect (for SSH automation)
        run: |
          sudo apt-get update && sudo apt-get install -y expect

      - name: Deploy to Minikube on Remote VM
        run: |
          echo "Starting deployment..."
          expect -c "
            spawn ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }}
            expect \"password:\"
            send \"${{ secrets.VM_PASSWORD }}\r\"
            expect \"$ \"

            send \"echo '✅ Connected to VM'\r\"

            # Ensure Minikube is Running
            send \"echo '🔄 Checking Minikube status...'\r\"
            send \"minikube status || minikube start --driver=docker\r\"

            # Run Kubernetes Deployment Commands
            send \"echo '❌ Deleting old Kubernetes resources...'\r\"
            send \"kubectl delete -f /Team4_k8s_App/deployment.yaml\r\"
            send \"kubectl delete -f /Team4_k8s_App/ingress.yaml\r\"
            send \"kubectl delete -f /Team4_k8s_App/service.yaml\r\"

            send \"echo '🚀 Applying new Kubernetes configurations...'\r\"
            send \"kubectl apply -f /Team4_k8s_App/service.yaml\r\"
            send \"kubectl apply -f /Team4_k8s_App/deployment.yaml\r\"
            send \"kubectl apply -f /Team4_k8s_App/ingress.yaml\r\"

            send \"echo '♻️ Restarting Kubernetes service...'\r\"
            send \"minikube service inventory-manager-service\r\"

            send \"exit\r\"
            interact
          "

      - name: Get Minikube Service URL
        run: |
          echo "Fetching Minikube service URL..."
          expect -c "
            spawn ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }}
            expect \"password:\"
            send \"${{ secrets.VM_PASSWORD }}\r\"
            expect \"$ \"

            send \"minikube service inventory-manager-service --url\r\"

            expect \"$ \"
            send \"exit\r\"
            interact
          "
