name: Deploy to Minikube

on:
  workflow_dispatch:  # Triggered manually or from test.yml
  push:
    branches:
      - master  # Deploy only on master branch updates

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest

      - name: Start Minikube
        run: |
          minikube start --driver=docker
          minikube status

      - name: Set up Docker
        run: |
          eval $(minikube docker-env)

      - name: Pull Latest Image
        run: |
          docker pull lfrown/inventory-manager:latest

      - name: Update Deployment
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl rollout restart deployment inventory-manager-deployment

      - name: Get Service URL
        run: |
          echo "Access your app at:"
          minikube service inventory-manager-service --url
